#!/bin/bash
set -euo pipefail

# Read /var/lib/buildkite-agent/.env/docker_password as DOCKER_PASSWORD
DOCKER_PASSWORD=$(cat /var/lib/buildkite-agent/.env/docker_password)

# Set DOCKER_PASSWORD as an environment variable
export DOCKER_PASSWORD

# PS: This is a prod-ready way, I know, use a secret manager instead